gText_Birch_Welcome:: @ 82C897B
	.string "My, my, my...\p"
	.string "What do we have here?\p"
	.string "Welcome to the world of Pokémon.\p"
	.string "Everyone here calls me Acacia,\p"
	.string "Sherry Acacia.\l"
	.string "Some even call me a Pokémon\n"
	.string "Professor.\l"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle those plotting evil on\p"
	.string "the world.\l"
	.string "we don't know everything about\n"
	.string "Pokémon because they're so mysterious.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I undertake research with\l"
	.string "Professor Birch.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a male?\n"
	.string "Or are you a female?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Interesting.\n"
	.string "What do you call yourself?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Yare Yare...\p"
	.string "You're {PLAYER}{KUN}, the one that my\n"
	.string "boss wants to recruit.\l"
	.string "I get it now.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Not only my hope lies on you, but\n"
	.string "other as well have faith in you.\p"
	.string "Now!\p"
	.string "Go do what you were destined to do\n"
	.string "for this forsaken region.\l"
	.string "$"
