Text_BootUpPC: @ 827265A
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Accedido al PC de ALGUIEN.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Ingresado al Sistema de Almacenamiento\n"
	.string "de POKéMON.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "Accedido al PC de {PLAYER}.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Accedido al PC de AREDIA.$"
