gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} fue enviado al PC\n"
	.string "de alguien.\p"
	.string "Se ha guardado en la CAJA\n"
	.string "“{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2} fue enviado al PC\nde LANETTE.\p"
	.string "Se ha guardado en la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "La CAJA “{STR_VAR_3}” del PC\n"
	.string "de alguien estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "La CAJA “{STR_VAR_3}” del PC\n"
	.string "de AREDIA estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "¡No queda sitio para más POKéMON!\p"
	.string "¡Las CAJAS POKéMON están llenas!$"

gText_NicknameThisPokemon:: @ 8273374
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
