Route13_MapScripts::
	.byte 0

Route13_EventScript_Yoshi::
	trainerbattle_single TRAINER_YOSHI, Route13_Text_YoshiIntro, Route13_Text_YoshiDefeat
	msgbox Route13_Text_YoshiPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Natalia::
	trainerbattle_single TRAINER_NATALIA, Route13_Text_NataliaIntro, Route13_Text_NataliaDefeat
	msgbox Route13_Text_NataliaPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Kenith::
	trainerbattle_single TRAINER_KENITH, Route13_Text_KenithIntro, Route13_Text_KenithDefeat
	msgbox Route13_Text_KenithPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Sandford::
	trainerbattle_single TRAINER_SANDFORD, Route13_Text_SandfordIntro, Route13_Text_SandfordDefeat
	msgbox Route13_Text_SandfordPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Stella::
	trainerbattle_single TRAINER_STELLA, Route13_Text_StellaIntro, Route13_Text_StellaDefeat
	msgbox Route13_Text_StellaPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Aniyah::
	trainerbattle_single TRAINER_ANIYAH, Route13_Text_AniyahIntro, Route13_Text_AniyahDefeat
	msgbox Route13_Text_AniyahPostBattle, MSGBOX_AUTOCLOSE
	end

Route13_EventScript_Wolfe::
	trainerbattle_single TRAINER_WOLFE, Route13_Text_WolfeIntro, Route13_Text_WolfeDefeat
	msgbox Route13_Text_WolfePostBattle, MSGBOX_AUTOCLOSE
	end